---
title: 'stplanr: A Package for Geographic Transport Data Science'
output:
  pdf_document:
    keep_tex: yes
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
  word_document: default
bibliography: references.bib
abstract: |
  Tools for transport planning should be flexible, scalable and well-integrated with geographic data. **stplanr** meets each of these criteria by providing functionality commonly needed for transport planning in R, with an emphasis on spatial transport data. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf', out.width='\\textwidth')
```

# Install and load stplanr

Install **stplanr** from CRAN:

```{r, eval=FALSE}
install.packages("stplanr")
```

It automatically loads the **sp** package, for plotting etc:

```{r}
library(stplanr)
```

# OD Data

Perhaps the most common type of aggregate-level transport information is origin-destination ('OD') data.
  

```{r}
data("flow", package = "stplanr")
head(flow[c(1:3, 12)]) # look at some od data
```

```{r}
data("cents", package = "stplanr")
as.data.frame(cents[1:3, -c(3,4)]) # look at some points
```

We use `od2line` to combine `flow` and `cents`, to join
the former to the latter. 

```{r, warning=FALSE}
l <- od2line(flow = flow, zones = cents)
plot(l)
```




## References

